schema: spec-driven
change: improve-wasm-accuracy
status: proposed
artifacts:
  proposal:
    status: done
  design:
    status: done
    dependsOn: [proposal]
  tasks:
    status: done
    dependsOn: [design]
apply:
  requires: [tasks]
