// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pipeline

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FaceBox struct {
	_tab flatbuffers.Struct
}

func (rcv *FaceBox) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FaceBox) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *FaceBox) X() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *FaceBox) MutateX(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *FaceBox) Y() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(2))
}
func (rcv *FaceBox) MutateY(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(2), n)
}

func (rcv *FaceBox) Width() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(4))
}
func (rcv *FaceBox) MutateWidth(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(4), n)
}

func (rcv *FaceBox) Height() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(6))
}
func (rcv *FaceBox) MutateHeight(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(6), n)
}

func (rcv *FaceBox) Confidence() float32 {
	return rcv._tab.GetFloat32(rcv._tab.Pos + flatbuffers.UOffsetT(8))
}
func (rcv *FaceBox) MutateConfidence(n float32) bool {
	return rcv._tab.MutateFloat32(rcv._tab.Pos+flatbuffers.UOffsetT(8), n)
}

func CreateFaceBox(builder *flatbuffers.Builder, x uint16, y uint16, width uint16, height uint16, confidence float32) flatbuffers.UOffsetT {
	builder.Prep(4, 12)
	builder.PrependFloat32(confidence)
	builder.PrependUint16(height)
	builder.PrependUint16(width)
	builder.PrependUint16(y)
	builder.PrependUint16(x)
	return builder.Offset()
}
