// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pipeline

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FaceDetectionResult struct {
	_tab flatbuffers.Table
}

func GetRootAsFaceDetectionResult(buf []byte, offset flatbuffers.UOffsetT) *FaceDetectionResult {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FaceDetectionResult{}
	x.Init(buf, n+offset)
	return x
}

func FinishFaceDetectionResultBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsFaceDetectionResult(buf []byte, offset flatbuffers.UOffsetT) *FaceDetectionResult {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FaceDetectionResult{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedFaceDetectionResultBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *FaceDetectionResult) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FaceDetectionResult) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FaceDetectionResult) FaceCount() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FaceDetectionResult) MutateFaceCount(n byte) bool {
	return rcv._tab.MutateByteSlot(4, n)
}

func (rcv *FaceDetectionResult) Faces(obj *FaceBox, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 12
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *FaceDetectionResult) FacesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *FaceDetectionResult) IdQualityMetrics(obj *QualityMetrics) *QualityMetrics {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(QualityMetrics)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *FaceDetectionResult) SelfieQualityMetrics(obj *QualityMetrics) *QualityMetrics {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(QualityMetrics)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func FaceDetectionResultStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func FaceDetectionResultAddFaceCount(builder *flatbuffers.Builder, faceCount byte) {
	builder.PrependByteSlot(0, faceCount, 0)
}
func FaceDetectionResultAddFaces(builder *flatbuffers.Builder, faces flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(faces), 0)
}
func FaceDetectionResultStartFacesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(12, numElems, 4)
}
func FaceDetectionResultAddIdQualityMetrics(builder *flatbuffers.Builder, idQualityMetrics flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(idQualityMetrics), 0)
}
func FaceDetectionResultAddSelfieQualityMetrics(builder *flatbuffers.Builder, selfieQualityMetrics flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(selfieQualityMetrics), 0)
}
func FaceDetectionResultEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
