// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pipeline

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FaceComparisonResult struct {
	_tab flatbuffers.Table
}

func GetRootAsFaceComparisonResult(buf []byte, offset flatbuffers.UOffsetT) *FaceComparisonResult {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FaceComparisonResult{}
	x.Init(buf, n+offset)
	return x
}

func FinishFaceComparisonResultBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsFaceComparisonResult(buf []byte, offset flatbuffers.UOffsetT) *FaceComparisonResult {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FaceComparisonResult{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedFaceComparisonResultBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *FaceComparisonResult) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FaceComparisonResult) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FaceComparisonResult) Status() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *FaceComparisonResult) Similarity() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *FaceComparisonResult) MutateSimilarity(n float32) bool {
	return rcv._tab.MutateFloat32Slot(6, n)
}

func (rcv *FaceComparisonResult) Matched() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *FaceComparisonResult) MutateMatched(n bool) bool {
	return rcv._tab.MutateBoolSlot(8, n)
}

func (rcv *FaceComparisonResult) IdFaceCount() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FaceComparisonResult) MutateIdFaceCount(n byte) bool {
	return rcv._tab.MutateByteSlot(10, n)
}

func (rcv *FaceComparisonResult) SelfieFaceCount() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FaceComparisonResult) MutateSelfieFaceCount(n byte) bool {
	return rcv._tab.MutateByteSlot(12, n)
}

func (rcv *FaceComparisonResult) ChecksJson() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func FaceComparisonResultStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func FaceComparisonResultAddStatus(builder *flatbuffers.Builder, status flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(status), 0)
}
func FaceComparisonResultAddSimilarity(builder *flatbuffers.Builder, similarity float32) {
	builder.PrependFloat32Slot(1, similarity, 0.0)
}
func FaceComparisonResultAddMatched(builder *flatbuffers.Builder, matched bool) {
	builder.PrependBoolSlot(2, matched, false)
}
func FaceComparisonResultAddIdFaceCount(builder *flatbuffers.Builder, idFaceCount byte) {
	builder.PrependByteSlot(3, idFaceCount, 0)
}
func FaceComparisonResultAddSelfieFaceCount(builder *flatbuffers.Builder, selfieFaceCount byte) {
	builder.PrependByteSlot(4, selfieFaceCount, 0)
}
func FaceComparisonResultAddChecksJson(builder *flatbuffers.Builder, checksJson flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(checksJson), 0)
}
func FaceComparisonResultEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
