// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pipeline

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FraudAnalysisResult struct {
	_tab flatbuffers.Table
}

func GetRootAsFraudAnalysisResult(buf []byte, offset flatbuffers.UOffsetT) *FraudAnalysisResult {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FraudAnalysisResult{}
	x.Init(buf, n+offset)
	return x
}

func FinishFraudAnalysisResultBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsFraudAnalysisResult(buf []byte, offset flatbuffers.UOffsetT) *FraudAnalysisResult {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FraudAnalysisResult{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedFraudAnalysisResultBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *FraudAnalysisResult) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FraudAnalysisResult) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FraudAnalysisResult) Status() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *FraudAnalysisResult) FakeProbability() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *FraudAnalysisResult) MutateFakeProbability(n float32) bool {
	return rcv._tab.MutateFloat32Slot(6, n)
}

func (rcv *FraudAnalysisResult) Issues(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *FraudAnalysisResult) IssuesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *FraudAnalysisResult) MetadataJson() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func FraudAnalysisResultStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func FraudAnalysisResultAddStatus(builder *flatbuffers.Builder, status flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(status), 0)
}
func FraudAnalysisResultAddFakeProbability(builder *flatbuffers.Builder, fakeProbability float32) {
	builder.PrependFloat32Slot(1, fakeProbability, 0.0)
}
func FraudAnalysisResultAddIssues(builder *flatbuffers.Builder, issues flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(issues), 0)
}
func FraudAnalysisResultStartIssuesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func FraudAnalysisResultAddMetadataJson(builder *flatbuffers.Builder, metadataJson flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(metadataJson), 0)
}
func FraudAnalysisResultEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
