// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pipeline

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ImageMetadata struct {
	_tab flatbuffers.Table
}

func GetRootAsImageMetadata(buf []byte, offset flatbuffers.UOffsetT) *ImageMetadata {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ImageMetadata{}
	x.Init(buf, n+offset)
	return x
}

func FinishImageMetadataBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsImageMetadata(buf []byte, offset flatbuffers.UOffsetT) *ImageMetadata {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ImageMetadata{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedImageMetadataBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ImageMetadata) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ImageMetadata) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ImageMetadata) Width() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ImageMetadata) MutateWidth(n uint16) bool {
	return rcv._tab.MutateUint16Slot(4, n)
}

func (rcv *ImageMetadata) Height() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ImageMetadata) MutateHeight(n uint16) bool {
	return rcv._tab.MutateUint16Slot(6, n)
}

func (rcv *ImageMetadata) Channels() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 3
}

func (rcv *ImageMetadata) MutateChannels(n byte) bool {
	return rcv._tab.MutateByteSlot(8, n)
}

func (rcv *ImageMetadata) FileSizeBytes() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ImageMetadata) MutateFileSizeBytes(n uint32) bool {
	return rcv._tab.MutateUint32Slot(10, n)
}

func (rcv *ImageMetadata) HashSha256() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ImageMetadataStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func ImageMetadataAddWidth(builder *flatbuffers.Builder, width uint16) {
	builder.PrependUint16Slot(0, width, 0)
}
func ImageMetadataAddHeight(builder *flatbuffers.Builder, height uint16) {
	builder.PrependUint16Slot(1, height, 0)
}
func ImageMetadataAddChannels(builder *flatbuffers.Builder, channels byte) {
	builder.PrependByteSlot(2, channels, 3)
}
func ImageMetadataAddFileSizeBytes(builder *flatbuffers.Builder, fileSizeBytes uint32) {
	builder.PrependUint32Slot(3, fileSizeBytes, 0)
}
func ImageMetadataAddHashSha256(builder *flatbuffers.Builder, hashSha256 flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(hashSha256), 0)
}
func ImageMetadataEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
