// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pipeline

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type LivenessResult struct {
	_tab flatbuffers.Table
}

func GetRootAsLivenessResult(buf []byte, offset flatbuffers.UOffsetT) *LivenessResult {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LivenessResult{}
	x.Init(buf, n+offset)
	return x
}

func FinishLivenessResultBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsLivenessResult(buf []byte, offset flatbuffers.UOffsetT) *LivenessResult {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &LivenessResult{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedLivenessResultBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *LivenessResult) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LivenessResult) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *LivenessResult) Status() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *LivenessResult) Score() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *LivenessResult) MutateScore(n float32) bool {
	return rcv._tab.MutateFloat32Slot(6, n)
}

func (rcv *LivenessResult) Passed() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *LivenessResult) MutatePassed(n bool) bool {
	return rcv._tab.MutateBoolSlot(8, n)
}

func (rcv *LivenessResult) Issues(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *LivenessResult) IssuesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func LivenessResultStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func LivenessResultAddStatus(builder *flatbuffers.Builder, status flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(status), 0)
}
func LivenessResultAddScore(builder *flatbuffers.Builder, score float32) {
	builder.PrependFloat32Slot(1, score, 0.0)
}
func LivenessResultAddPassed(builder *flatbuffers.Builder, passed bool) {
	builder.PrependBoolSlot(2, passed, false)
}
func LivenessResultAddIssues(builder *flatbuffers.Builder, issues flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(issues), 0)
}
func LivenessResultStartIssuesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func LivenessResultEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
