// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pipeline

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type OcrField struct {
	_tab flatbuffers.Table
}

func GetRootAsOcrField(buf []byte, offset flatbuffers.UOffsetT) *OcrField {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &OcrField{}
	x.Init(buf, n+offset)
	return x
}

func FinishOcrFieldBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsOcrField(buf []byte, offset flatbuffers.UOffsetT) *OcrField {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &OcrField{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedOcrFieldBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *OcrField) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *OcrField) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *OcrField) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *OcrField) Value() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *OcrField) Confidence() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *OcrField) MutateConfidence(n float32) bool {
	return rcv._tab.MutateFloat32Slot(8, n)
}

func OcrFieldStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func OcrFieldAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}
func OcrFieldAddValue(builder *flatbuffers.Builder, value flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(value), 0)
}
func OcrFieldAddConfidence(builder *flatbuffers.Builder, confidence float32) {
	builder.PrependFloat32Slot(2, confidence, 0.0)
}
func OcrFieldEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
