// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pipeline

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PipelineStepResult struct {
	_tab flatbuffers.Table
}

func GetRootAsPipelineStepResult(buf []byte, offset flatbuffers.UOffsetT) *PipelineStepResult {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PipelineStepResult{}
	x.Init(buf, n+offset)
	return x
}

func FinishPipelineStepResultBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPipelineStepResult(buf []byte, offset flatbuffers.UOffsetT) *PipelineStepResult {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PipelineStepResult{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPipelineStepResultBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PipelineStepResult) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PipelineStepResult) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PipelineStepResult) StepName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PipelineStepResult) Status() PipelineStatus {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return PipelineStatus(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *PipelineStepResult) MutateStatus(n PipelineStatus) bool {
	return rcv._tab.MutateInt8Slot(6, int8(n))
}

func (rcv *PipelineStepResult) StartedAtMs() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PipelineStepResult) MutateStartedAtMs(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func (rcv *PipelineStepResult) DurationMs() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PipelineStepResult) MutateDurationMs(n uint32) bool {
	return rcv._tab.MutateUint32Slot(10, n)
}

func (rcv *PipelineStepResult) ErrorMessage() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func PipelineStepResultStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func PipelineStepResultAddStepName(builder *flatbuffers.Builder, stepName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(stepName), 0)
}
func PipelineStepResultAddStatus(builder *flatbuffers.Builder, status PipelineStatus) {
	builder.PrependInt8Slot(1, int8(status), 0)
}
func PipelineStepResultAddStartedAtMs(builder *flatbuffers.Builder, startedAtMs uint64) {
	builder.PrependUint64Slot(2, startedAtMs, 0)
}
func PipelineStepResultAddDurationMs(builder *flatbuffers.Builder, durationMs uint32) {
	builder.PrependUint32Slot(3, durationMs, 0)
}
func PipelineStepResultAddErrorMessage(builder *flatbuffers.Builder, errorMessage flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(errorMessage), 0)
}
func PipelineStepResultEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
