// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pipeline

import "strconv"

type PipelineStatus int8

const (
	PipelineStatuspending   PipelineStatus = 0
	PipelineStatusrunning   PipelineStatus = 1
	PipelineStatuscompleted PipelineStatus = 2
	PipelineStatusfailed    PipelineStatus = 3
)

var EnumNamesPipelineStatus = map[PipelineStatus]string{
	PipelineStatuspending:   "pending",
	PipelineStatusrunning:   "running",
	PipelineStatuscompleted: "completed",
	PipelineStatusfailed:    "failed",
}

var EnumValuesPipelineStatus = map[string]PipelineStatus{
	"pending":   PipelineStatuspending,
	"running":   PipelineStatusrunning,
	"completed": PipelineStatuscompleted,
	"failed":    PipelineStatusfailed,
}

func (v PipelineStatus) String() string {
	if s, ok := EnumNamesPipelineStatus[v]; ok {
		return s
	}
	return "PipelineStatus(" + strconv.FormatInt(int64(v), 10) + ")"
}
