// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pipeline

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PipelineResult struct {
	_tab flatbuffers.Table
}

func GetRootAsPipelineResult(buf []byte, offset flatbuffers.UOffsetT) *PipelineResult {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PipelineResult{}
	x.Init(buf, n+offset)
	return x
}

func FinishPipelineResultBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPipelineResult(buf []byte, offset flatbuffers.UOffsetT) *PipelineResult {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PipelineResult{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPipelineResultBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PipelineResult) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PipelineResult) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PipelineResult) IdImage(obj *ImageMetadata) *ImageMetadata {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(ImageMetadata)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *PipelineResult) SelfieImage(obj *ImageMetadata) *ImageMetadata {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(ImageMetadata)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *PipelineResult) Quality(obj *QualityMetrics) *QualityMetrics {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(QualityMetrics)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *PipelineResult) FaceDetection(obj *FaceDetectionResult) *FaceDetectionResult {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(FaceDetectionResult)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *PipelineResult) Ocr(obj *OcrResult) *OcrResult {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(OcrResult)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *PipelineResult) FaceComparison(obj *FaceComparisonResult) *FaceComparisonResult {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(FaceComparisonResult)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *PipelineResult) Liveness(obj *LivenessResult) *LivenessResult {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(LivenessResult)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *PipelineResult) Fraud(obj *FraudAnalysisResult) *FraudAnalysisResult {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(FraudAnalysisResult)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *PipelineResult) OverallScore() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *PipelineResult) MutateOverallScore(n float32) bool {
	return rcv._tab.MutateFloat32Slot(20, n)
}

func (rcv *PipelineResult) FinalStatus() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PipelineResult) Steps(obj *PipelineStepResult, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *PipelineResult) StepsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *PipelineResult) Error() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func PipelineResultStart(builder *flatbuffers.Builder) {
	builder.StartObject(12)
}
func PipelineResultAddIdImage(builder *flatbuffers.Builder, idImage flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(idImage), 0)
}
func PipelineResultAddSelfieImage(builder *flatbuffers.Builder, selfieImage flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(selfieImage), 0)
}
func PipelineResultAddQuality(builder *flatbuffers.Builder, quality flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(quality), 0)
}
func PipelineResultAddFaceDetection(builder *flatbuffers.Builder, faceDetection flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(faceDetection), 0)
}
func PipelineResultAddOcr(builder *flatbuffers.Builder, ocr flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(ocr), 0)
}
func PipelineResultAddFaceComparison(builder *flatbuffers.Builder, faceComparison flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(faceComparison), 0)
}
func PipelineResultAddLiveness(builder *flatbuffers.Builder, liveness flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(liveness), 0)
}
func PipelineResultAddFraud(builder *flatbuffers.Builder, fraud flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(fraud), 0)
}
func PipelineResultAddOverallScore(builder *flatbuffers.Builder, overallScore float32) {
	builder.PrependFloat32Slot(8, overallScore, 0.0)
}
func PipelineResultAddFinalStatus(builder *flatbuffers.Builder, finalStatus flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(9, flatbuffers.UOffsetT(finalStatus), 0)
}
func PipelineResultAddSteps(builder *flatbuffers.Builder, steps flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(10, flatbuffers.UOffsetT(steps), 0)
}
func PipelineResultStartStepsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func PipelineResultAddError(builder *flatbuffers.Builder, error flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(11, flatbuffers.UOffsetT(error), 0)
}
func PipelineResultEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
