// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pipeline

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type QualityMetrics struct {
	_tab flatbuffers.Table
}

func GetRootAsQualityMetrics(buf []byte, offset flatbuffers.UOffsetT) *QualityMetrics {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &QualityMetrics{}
	x.Init(buf, n+offset)
	return x
}

func FinishQualityMetricsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsQualityMetrics(buf []byte, offset flatbuffers.UOffsetT) *QualityMetrics {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &QualityMetrics{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedQualityMetricsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *QualityMetrics) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *QualityMetrics) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *QualityMetrics) QualityScore() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *QualityMetrics) MutateQualityScore(n float32) bool {
	return rcv._tab.MutateFloat32Slot(4, n)
}

func (rcv *QualityMetrics) Brightness() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *QualityMetrics) MutateBrightness(n float32) bool {
	return rcv._tab.MutateFloat32Slot(6, n)
}

func (rcv *QualityMetrics) Contrast() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *QualityMetrics) MutateContrast(n float32) bool {
	return rcv._tab.MutateFloat32Slot(8, n)
}

func (rcv *QualityMetrics) Sharpness() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *QualityMetrics) MutateSharpness(n float32) bool {
	return rcv._tab.MutateFloat32Slot(10, n)
}

func (rcv *QualityMetrics) BlurScore() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *QualityMetrics) MutateBlurScore(n float32) bool {
	return rcv._tab.MutateFloat32Slot(12, n)
}

func (rcv *QualityMetrics) NoiseEstimate() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *QualityMetrics) MutateNoiseEstimate(n float32) bool {
	return rcv._tab.MutateFloat32Slot(14, n)
}

func (rcv *QualityMetrics) DynamicRange() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *QualityMetrics) MutateDynamicRange(n float32) bool {
	return rcv._tab.MutateFloat32Slot(16, n)
}

func (rcv *QualityMetrics) Exposure() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *QualityMetrics) MutateExposure(n float32) bool {
	return rcv._tab.MutateFloat32Slot(18, n)
}

func (rcv *QualityMetrics) IsBlurry() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *QualityMetrics) MutateIsBlurry(n bool) bool {
	return rcv._tab.MutateBoolSlot(20, n)
}

func (rcv *QualityMetrics) IsLowLight() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *QualityMetrics) MutateIsLowLight(n bool) bool {
	return rcv._tab.MutateBoolSlot(22, n)
}

func (rcv *QualityMetrics) IsOverexposed() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *QualityMetrics) MutateIsOverexposed(n bool) bool {
	return rcv._tab.MutateBoolSlot(24, n)
}

func (rcv *QualityMetrics) FacePresent() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *QualityMetrics) MutateFacePresent(n bool) bool {
	return rcv._tab.MutateBoolSlot(26, n)
}

func QualityMetricsStart(builder *flatbuffers.Builder) {
	builder.StartObject(12)
}
func QualityMetricsAddQualityScore(builder *flatbuffers.Builder, qualityScore float32) {
	builder.PrependFloat32Slot(0, qualityScore, 0.0)
}
func QualityMetricsAddBrightness(builder *flatbuffers.Builder, brightness float32) {
	builder.PrependFloat32Slot(1, brightness, 0.0)
}
func QualityMetricsAddContrast(builder *flatbuffers.Builder, contrast float32) {
	builder.PrependFloat32Slot(2, contrast, 0.0)
}
func QualityMetricsAddSharpness(builder *flatbuffers.Builder, sharpness float32) {
	builder.PrependFloat32Slot(3, sharpness, 0.0)
}
func QualityMetricsAddBlurScore(builder *flatbuffers.Builder, blurScore float32) {
	builder.PrependFloat32Slot(4, blurScore, 0.0)
}
func QualityMetricsAddNoiseEstimate(builder *flatbuffers.Builder, noiseEstimate float32) {
	builder.PrependFloat32Slot(5, noiseEstimate, 0.0)
}
func QualityMetricsAddDynamicRange(builder *flatbuffers.Builder, dynamicRange float32) {
	builder.PrependFloat32Slot(6, dynamicRange, 0.0)
}
func QualityMetricsAddExposure(builder *flatbuffers.Builder, exposure float32) {
	builder.PrependFloat32Slot(7, exposure, 0.0)
}
func QualityMetricsAddIsBlurry(builder *flatbuffers.Builder, isBlurry bool) {
	builder.PrependBoolSlot(8, isBlurry, false)
}
func QualityMetricsAddIsLowLight(builder *flatbuffers.Builder, isLowLight bool) {
	builder.PrependBoolSlot(9, isLowLight, false)
}
func QualityMetricsAddIsOverexposed(builder *flatbuffers.Builder, isOverexposed bool) {
	builder.PrependBoolSlot(10, isOverexposed, false)
}
func QualityMetricsAddFacePresent(builder *flatbuffers.Builder, facePresent bool) {
	builder.PrependBoolSlot(11, facePresent, false)
}
func QualityMetricsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
