# automatically generated by the FlatBuffers compiler, do not modify

# namespace: pipeline

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FaceDetectionResult(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FaceDetectionResult()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFaceDetectionResult(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FaceDetectionResult
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FaceDetectionResult
    def FaceCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # FaceDetectionResult
    def Faces(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 12
            from bdrs.pipeline.FaceBox import FaceBox
            obj = FaceBox()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FaceDetectionResult
    def FacesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FaceDetectionResult
    def FacesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # FaceDetectionResult
    def IdQualityMetrics(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from bdrs.pipeline.QualityMetrics import QualityMetrics
            obj = QualityMetrics()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FaceDetectionResult
    def SelfieQualityMetrics(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from bdrs.pipeline.QualityMetrics import QualityMetrics
            obj = QualityMetrics()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def FaceDetectionResultStart(builder):
    builder.StartObject(4)

def Start(builder):
    FaceDetectionResultStart(builder)

def FaceDetectionResultAddFaceCount(builder, faceCount):
    builder.PrependUint8Slot(0, faceCount, 0)

def AddFaceCount(builder, faceCount):
    FaceDetectionResultAddFaceCount(builder, faceCount)

def FaceDetectionResultAddFaces(builder, faces):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(faces), 0)

def AddFaces(builder, faces):
    FaceDetectionResultAddFaces(builder, faces)

def FaceDetectionResultStartFacesVector(builder, numElems):
    return builder.StartVector(12, numElems, 4)

def StartFacesVector(builder, numElems):
    return FaceDetectionResultStartFacesVector(builder, numElems)

def FaceDetectionResultAddIdQualityMetrics(builder, idQualityMetrics):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(idQualityMetrics), 0)

def AddIdQualityMetrics(builder, idQualityMetrics):
    FaceDetectionResultAddIdQualityMetrics(builder, idQualityMetrics)

def FaceDetectionResultAddSelfieQualityMetrics(builder, selfieQualityMetrics):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(selfieQualityMetrics), 0)

def AddSelfieQualityMetrics(builder, selfieQualityMetrics):
    FaceDetectionResultAddSelfieQualityMetrics(builder, selfieQualityMetrics)

def FaceDetectionResultEnd(builder):
    return builder.EndObject()

def End(builder):
    return FaceDetectionResultEnd(builder)
