# automatically generated by the FlatBuffers compiler, do not modify

# namespace: pipeline

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FaceBox(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 12

    # FaceBox
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FaceBox
    def X(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # FaceBox
    def Y(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(2))
    # FaceBox
    def Width(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # FaceBox
    def Height(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(6))
    # FaceBox
    def Confidence(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))

def CreateFaceBox(builder, x, y, width, height, confidence):
    builder.Prep(4, 12)
    builder.PrependFloat32(confidence)
    builder.PrependUint16(height)
    builder.PrependUint16(width)
    builder.PrependUint16(y)
    builder.PrependUint16(x)
    return builder.Offset()
