# automatically generated by the FlatBuffers compiler, do not modify

# namespace: pipeline

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FaceComparisonResult(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FaceComparisonResult()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFaceComparisonResult(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FaceComparisonResult
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FaceComparisonResult
    def Status(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FaceComparisonResult
    def Similarity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # FaceComparisonResult
    def Matched(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # FaceComparisonResult
    def IdFaceCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # FaceComparisonResult
    def SelfieFaceCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # FaceComparisonResult
    def ChecksJson(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def FaceComparisonResultStart(builder):
    builder.StartObject(6)

def Start(builder):
    FaceComparisonResultStart(builder)

def FaceComparisonResultAddStatus(builder, status):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(status), 0)

def AddStatus(builder, status):
    FaceComparisonResultAddStatus(builder, status)

def FaceComparisonResultAddSimilarity(builder, similarity):
    builder.PrependFloat32Slot(1, similarity, 0.0)

def AddSimilarity(builder, similarity):
    FaceComparisonResultAddSimilarity(builder, similarity)

def FaceComparisonResultAddMatched(builder, matched):
    builder.PrependBoolSlot(2, matched, 0)

def AddMatched(builder, matched):
    FaceComparisonResultAddMatched(builder, matched)

def FaceComparisonResultAddIdFaceCount(builder, idFaceCount):
    builder.PrependUint8Slot(3, idFaceCount, 0)

def AddIdFaceCount(builder, idFaceCount):
    FaceComparisonResultAddIdFaceCount(builder, idFaceCount)

def FaceComparisonResultAddSelfieFaceCount(builder, selfieFaceCount):
    builder.PrependUint8Slot(4, selfieFaceCount, 0)

def AddSelfieFaceCount(builder, selfieFaceCount):
    FaceComparisonResultAddSelfieFaceCount(builder, selfieFaceCount)

def FaceComparisonResultAddChecksJson(builder, checksJson):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(checksJson), 0)

def AddChecksJson(builder, checksJson):
    FaceComparisonResultAddChecksJson(builder, checksJson)

def FaceComparisonResultEnd(builder):
    return builder.EndObject()

def End(builder):
    return FaceComparisonResultEnd(builder)
