# automatically generated by the FlatBuffers compiler, do not modify

# namespace: pipeline

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FraudAnalysisResult(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FraudAnalysisResult()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFraudAnalysisResult(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FraudAnalysisResult
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FraudAnalysisResult
    def Status(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FraudAnalysisResult
    def FakeProbability(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # FraudAnalysisResult
    def Issues(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # FraudAnalysisResult
    def IssuesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FraudAnalysisResult
    def IssuesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # FraudAnalysisResult
    def MetadataJson(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def FraudAnalysisResultStart(builder):
    builder.StartObject(4)

def Start(builder):
    FraudAnalysisResultStart(builder)

def FraudAnalysisResultAddStatus(builder, status):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(status), 0)

def AddStatus(builder, status):
    FraudAnalysisResultAddStatus(builder, status)

def FraudAnalysisResultAddFakeProbability(builder, fakeProbability):
    builder.PrependFloat32Slot(1, fakeProbability, 0.0)

def AddFakeProbability(builder, fakeProbability):
    FraudAnalysisResultAddFakeProbability(builder, fakeProbability)

def FraudAnalysisResultAddIssues(builder, issues):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(issues), 0)

def AddIssues(builder, issues):
    FraudAnalysisResultAddIssues(builder, issues)

def FraudAnalysisResultStartIssuesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartIssuesVector(builder, numElems):
    return FraudAnalysisResultStartIssuesVector(builder, numElems)

def FraudAnalysisResultAddMetadataJson(builder, metadataJson):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(metadataJson), 0)

def AddMetadataJson(builder, metadataJson):
    FraudAnalysisResultAddMetadataJson(builder, metadataJson)

def FraudAnalysisResultEnd(builder):
    return builder.EndObject()

def End(builder):
    return FraudAnalysisResultEnd(builder)
