# automatically generated by the FlatBuffers compiler, do not modify

# namespace: pipeline

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ImageMetadata(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ImageMetadata()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsImageMetadata(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ImageMetadata
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ImageMetadata
    def Width(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # ImageMetadata
    def Height(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # ImageMetadata
    def Channels(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 3

    # ImageMetadata
    def FileSizeBytes(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ImageMetadata
    def HashSha256(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ImageMetadataStart(builder):
    builder.StartObject(5)

def Start(builder):
    ImageMetadataStart(builder)

def ImageMetadataAddWidth(builder, width):
    builder.PrependUint16Slot(0, width, 0)

def AddWidth(builder, width):
    ImageMetadataAddWidth(builder, width)

def ImageMetadataAddHeight(builder, height):
    builder.PrependUint16Slot(1, height, 0)

def AddHeight(builder, height):
    ImageMetadataAddHeight(builder, height)

def ImageMetadataAddChannels(builder, channels):
    builder.PrependUint8Slot(2, channels, 3)

def AddChannels(builder, channels):
    ImageMetadataAddChannels(builder, channels)

def ImageMetadataAddFileSizeBytes(builder, fileSizeBytes):
    builder.PrependUint32Slot(3, fileSizeBytes, 0)

def AddFileSizeBytes(builder, fileSizeBytes):
    ImageMetadataAddFileSizeBytes(builder, fileSizeBytes)

def ImageMetadataAddHashSha256(builder, hashSha256):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(hashSha256), 0)

def AddHashSha256(builder, hashSha256):
    ImageMetadataAddHashSha256(builder, hashSha256)

def ImageMetadataEnd(builder):
    return builder.EndObject()

def End(builder):
    return ImageMetadataEnd(builder)
