# automatically generated by the FlatBuffers compiler, do not modify

# namespace: pipeline

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class LivenessResult(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LivenessResult()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLivenessResult(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # LivenessResult
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LivenessResult
    def Status(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LivenessResult
    def Score(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # LivenessResult
    def Passed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # LivenessResult
    def Issues(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # LivenessResult
    def IssuesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # LivenessResult
    def IssuesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

def LivenessResultStart(builder):
    builder.StartObject(4)

def Start(builder):
    LivenessResultStart(builder)

def LivenessResultAddStatus(builder, status):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(status), 0)

def AddStatus(builder, status):
    LivenessResultAddStatus(builder, status)

def LivenessResultAddScore(builder, score):
    builder.PrependFloat32Slot(1, score, 0.0)

def AddScore(builder, score):
    LivenessResultAddScore(builder, score)

def LivenessResultAddPassed(builder, passed):
    builder.PrependBoolSlot(2, passed, 0)

def AddPassed(builder, passed):
    LivenessResultAddPassed(builder, passed)

def LivenessResultAddIssues(builder, issues):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(issues), 0)

def AddIssues(builder, issues):
    LivenessResultAddIssues(builder, issues)

def LivenessResultStartIssuesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartIssuesVector(builder, numElems):
    return LivenessResultStartIssuesVector(builder, numElems)

def LivenessResultEnd(builder):
    return builder.EndObject()

def End(builder):
    return LivenessResultEnd(builder)
