# automatically generated by the FlatBuffers compiler, do not modify

# namespace: pipeline

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class OcrField(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = OcrField()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsOcrField(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # OcrField
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # OcrField
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # OcrField
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # OcrField
    def Confidence(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def OcrFieldStart(builder):
    builder.StartObject(3)

def Start(builder):
    OcrFieldStart(builder)

def OcrFieldAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    OcrFieldAddName(builder, name)

def OcrFieldAddValue(builder, value):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0)

def AddValue(builder, value):
    OcrFieldAddValue(builder, value)

def OcrFieldAddConfidence(builder, confidence):
    builder.PrependFloat32Slot(2, confidence, 0.0)

def AddConfidence(builder, confidence):
    OcrFieldAddConfidence(builder, confidence)

def OcrFieldEnd(builder):
    return builder.EndObject()

def End(builder):
    return OcrFieldEnd(builder)
