# automatically generated by the FlatBuffers compiler, do not modify

# namespace: pipeline

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class OcrResult(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = OcrResult()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsOcrResult(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # OcrResult
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # OcrResult
    def Status(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # OcrResult
    def Confidence(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # OcrResult
    def Fields(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from bdrs.pipeline.OcrField import OcrField
            obj = OcrField()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # OcrResult
    def FieldsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # OcrResult
    def FieldsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # OcrResult
    def RawText(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # OcrResult
    def RawTextLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # OcrResult
    def RawTextIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # OcrResult
    def DocumentValidation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # OcrResult
    def Issues(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # OcrResult
    def IssuesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # OcrResult
    def IssuesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # OcrResult
    def Engine(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def OcrResultStart(builder):
    builder.StartObject(7)

def Start(builder):
    OcrResultStart(builder)

def OcrResultAddStatus(builder, status):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(status), 0)

def AddStatus(builder, status):
    OcrResultAddStatus(builder, status)

def OcrResultAddConfidence(builder, confidence):
    builder.PrependFloat32Slot(1, confidence, 0.0)

def AddConfidence(builder, confidence):
    OcrResultAddConfidence(builder, confidence)

def OcrResultAddFields(builder, fields):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(fields), 0)

def AddFields(builder, fields):
    OcrResultAddFields(builder, fields)

def OcrResultStartFieldsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartFieldsVector(builder, numElems):
    return OcrResultStartFieldsVector(builder, numElems)

def OcrResultAddRawText(builder, rawText):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(rawText), 0)

def AddRawText(builder, rawText):
    OcrResultAddRawText(builder, rawText)

def OcrResultStartRawTextVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartRawTextVector(builder, numElems):
    return OcrResultStartRawTextVector(builder, numElems)

def OcrResultAddDocumentValidation(builder, documentValidation):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(documentValidation), 0)

def AddDocumentValidation(builder, documentValidation):
    OcrResultAddDocumentValidation(builder, documentValidation)

def OcrResultAddIssues(builder, issues):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(issues), 0)

def AddIssues(builder, issues):
    OcrResultAddIssues(builder, issues)

def OcrResultStartIssuesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartIssuesVector(builder, numElems):
    return OcrResultStartIssuesVector(builder, numElems)

def OcrResultAddEngine(builder, engine):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(engine), 0)

def AddEngine(builder, engine):
    OcrResultAddEngine(builder, engine)

def OcrResultEnd(builder):
    return builder.EndObject()

def End(builder):
    return OcrResultEnd(builder)
