# automatically generated by the FlatBuffers compiler, do not modify

# namespace: pipeline

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PipelineResult(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PipelineResult()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPipelineResult(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PipelineResult
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PipelineResult
    def IdImage(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from bdrs.pipeline.ImageMetadata import ImageMetadata
            obj = ImageMetadata()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PipelineResult
    def SelfieImage(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from bdrs.pipeline.ImageMetadata import ImageMetadata
            obj = ImageMetadata()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PipelineResult
    def Quality(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from bdrs.pipeline.QualityMetrics import QualityMetrics
            obj = QualityMetrics()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PipelineResult
    def FaceDetection(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from bdrs.pipeline.FaceDetectionResult import FaceDetectionResult
            obj = FaceDetectionResult()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PipelineResult
    def Ocr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from bdrs.pipeline.OcrResult import OcrResult
            obj = OcrResult()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PipelineResult
    def FaceComparison(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from bdrs.pipeline.FaceComparisonResult import FaceComparisonResult
            obj = FaceComparisonResult()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PipelineResult
    def Liveness(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from bdrs.pipeline.LivenessResult import LivenessResult
            obj = LivenessResult()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PipelineResult
    def Fraud(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from bdrs.pipeline.FraudAnalysisResult import FraudAnalysisResult
            obj = FraudAnalysisResult()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PipelineResult
    def OverallScore(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # PipelineResult
    def FinalStatus(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PipelineResult
    def Steps(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from bdrs.pipeline.PipelineStepResult import PipelineStepResult
            obj = PipelineStepResult()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PipelineResult
    def StepsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # PipelineResult
    def StepsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        return o == 0

    # PipelineResult
    def Error(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def PipelineResultStart(builder):
    builder.StartObject(12)

def Start(builder):
    PipelineResultStart(builder)

def PipelineResultAddIdImage(builder, idImage):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(idImage), 0)

def AddIdImage(builder, idImage):
    PipelineResultAddIdImage(builder, idImage)

def PipelineResultAddSelfieImage(builder, selfieImage):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(selfieImage), 0)

def AddSelfieImage(builder, selfieImage):
    PipelineResultAddSelfieImage(builder, selfieImage)

def PipelineResultAddQuality(builder, quality):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(quality), 0)

def AddQuality(builder, quality):
    PipelineResultAddQuality(builder, quality)

def PipelineResultAddFaceDetection(builder, faceDetection):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(faceDetection), 0)

def AddFaceDetection(builder, faceDetection):
    PipelineResultAddFaceDetection(builder, faceDetection)

def PipelineResultAddOcr(builder, ocr):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(ocr), 0)

def AddOcr(builder, ocr):
    PipelineResultAddOcr(builder, ocr)

def PipelineResultAddFaceComparison(builder, faceComparison):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(faceComparison), 0)

def AddFaceComparison(builder, faceComparison):
    PipelineResultAddFaceComparison(builder, faceComparison)

def PipelineResultAddLiveness(builder, liveness):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(liveness), 0)

def AddLiveness(builder, liveness):
    PipelineResultAddLiveness(builder, liveness)

def PipelineResultAddFraud(builder, fraud):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(fraud), 0)

def AddFraud(builder, fraud):
    PipelineResultAddFraud(builder, fraud)

def PipelineResultAddOverallScore(builder, overallScore):
    builder.PrependFloat32Slot(8, overallScore, 0.0)

def AddOverallScore(builder, overallScore):
    PipelineResultAddOverallScore(builder, overallScore)

def PipelineResultAddFinalStatus(builder, finalStatus):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(finalStatus), 0)

def AddFinalStatus(builder, finalStatus):
    PipelineResultAddFinalStatus(builder, finalStatus)

def PipelineResultAddSteps(builder, steps):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(steps), 0)

def AddSteps(builder, steps):
    PipelineResultAddSteps(builder, steps)

def PipelineResultStartStepsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartStepsVector(builder, numElems):
    return PipelineResultStartStepsVector(builder, numElems)

def PipelineResultAddError(builder, error):
    builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(error), 0)

def AddError(builder, error):
    PipelineResultAddError(builder, error)

def PipelineResultEnd(builder):
    return builder.EndObject()

def End(builder):
    return PipelineResultEnd(builder)
