# automatically generated by the FlatBuffers compiler, do not modify

# namespace: pipeline

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PipelineStepResult(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PipelineStepResult()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPipelineStepResult(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PipelineStepResult
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PipelineStepResult
    def StepName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PipelineStepResult
    def Status(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # PipelineStepResult
    def StartedAtMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # PipelineStepResult
    def DurationMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # PipelineStepResult
    def ErrorMessage(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def PipelineStepResultStart(builder):
    builder.StartObject(5)

def Start(builder):
    PipelineStepResultStart(builder)

def PipelineStepResultAddStepName(builder, stepName):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(stepName), 0)

def AddStepName(builder, stepName):
    PipelineStepResultAddStepName(builder, stepName)

def PipelineStepResultAddStatus(builder, status):
    builder.PrependInt8Slot(1, status, 0)

def AddStatus(builder, status):
    PipelineStepResultAddStatus(builder, status)

def PipelineStepResultAddStartedAtMs(builder, startedAtMs):
    builder.PrependUint64Slot(2, startedAtMs, 0)

def AddStartedAtMs(builder, startedAtMs):
    PipelineStepResultAddStartedAtMs(builder, startedAtMs)

def PipelineStepResultAddDurationMs(builder, durationMs):
    builder.PrependUint32Slot(3, durationMs, 0)

def AddDurationMs(builder, durationMs):
    PipelineStepResultAddDurationMs(builder, durationMs)

def PipelineStepResultAddErrorMessage(builder, errorMessage):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(errorMessage), 0)

def AddErrorMessage(builder, errorMessage):
    PipelineStepResultAddErrorMessage(builder, errorMessage)

def PipelineStepResultEnd(builder):
    return builder.EndObject()

def End(builder):
    return PipelineStepResultEnd(builder)
