# automatically generated by the FlatBuffers compiler, do not modify

# namespace: pipeline

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class QualityMetrics(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = QualityMetrics()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsQualityMetrics(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # QualityMetrics
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # QualityMetrics
    def QualityScore(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # QualityMetrics
    def Brightness(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # QualityMetrics
    def Contrast(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # QualityMetrics
    def Sharpness(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # QualityMetrics
    def BlurScore(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # QualityMetrics
    def NoiseEstimate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # QualityMetrics
    def DynamicRange(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # QualityMetrics
    def Exposure(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # QualityMetrics
    def IsBlurry(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # QualityMetrics
    def IsLowLight(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # QualityMetrics
    def IsOverexposed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # QualityMetrics
    def FacePresent(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def QualityMetricsStart(builder):
    builder.StartObject(12)

def Start(builder):
    QualityMetricsStart(builder)

def QualityMetricsAddQualityScore(builder, qualityScore):
    builder.PrependFloat32Slot(0, qualityScore, 0.0)

def AddQualityScore(builder, qualityScore):
    QualityMetricsAddQualityScore(builder, qualityScore)

def QualityMetricsAddBrightness(builder, brightness):
    builder.PrependFloat32Slot(1, brightness, 0.0)

def AddBrightness(builder, brightness):
    QualityMetricsAddBrightness(builder, brightness)

def QualityMetricsAddContrast(builder, contrast):
    builder.PrependFloat32Slot(2, contrast, 0.0)

def AddContrast(builder, contrast):
    QualityMetricsAddContrast(builder, contrast)

def QualityMetricsAddSharpness(builder, sharpness):
    builder.PrependFloat32Slot(3, sharpness, 0.0)

def AddSharpness(builder, sharpness):
    QualityMetricsAddSharpness(builder, sharpness)

def QualityMetricsAddBlurScore(builder, blurScore):
    builder.PrependFloat32Slot(4, blurScore, 0.0)

def AddBlurScore(builder, blurScore):
    QualityMetricsAddBlurScore(builder, blurScore)

def QualityMetricsAddNoiseEstimate(builder, noiseEstimate):
    builder.PrependFloat32Slot(5, noiseEstimate, 0.0)

def AddNoiseEstimate(builder, noiseEstimate):
    QualityMetricsAddNoiseEstimate(builder, noiseEstimate)

def QualityMetricsAddDynamicRange(builder, dynamicRange):
    builder.PrependFloat32Slot(6, dynamicRange, 0.0)

def AddDynamicRange(builder, dynamicRange):
    QualityMetricsAddDynamicRange(builder, dynamicRange)

def QualityMetricsAddExposure(builder, exposure):
    builder.PrependFloat32Slot(7, exposure, 0.0)

def AddExposure(builder, exposure):
    QualityMetricsAddExposure(builder, exposure)

def QualityMetricsAddIsBlurry(builder, isBlurry):
    builder.PrependBoolSlot(8, isBlurry, 0)

def AddIsBlurry(builder, isBlurry):
    QualityMetricsAddIsBlurry(builder, isBlurry)

def QualityMetricsAddIsLowLight(builder, isLowLight):
    builder.PrependBoolSlot(9, isLowLight, 0)

def AddIsLowLight(builder, isLowLight):
    QualityMetricsAddIsLowLight(builder, isLowLight)

def QualityMetricsAddIsOverexposed(builder, isOverexposed):
    builder.PrependBoolSlot(10, isOverexposed, 0)

def AddIsOverexposed(builder, isOverexposed):
    QualityMetricsAddIsOverexposed(builder, isOverexposed)

def QualityMetricsAddFacePresent(builder, facePresent):
    builder.PrependBoolSlot(11, facePresent, 0)

def AddFacePresent(builder, facePresent):
    QualityMetricsAddFacePresent(builder, facePresent)

def QualityMetricsEnd(builder):
    return builder.EndObject()

def End(builder):
    return QualityMetricsEnd(builder)
